### ISSUE TITLE
Add config file

### ISSUE THREAD

**Issue by Khanx** [Khanx/SimpleWater#3]
Add a config file where you can set the spreadDistance and the spreadSpeed

**Comment by Dorky106** [comment]
You'll be able to add the config folder if any (relative of the mod folder) to the mod manager, though it'll just default to the mod folder.
Also if you use a name different from config.json you'll also have to put in that info too.

Also due to seeing this checked the mod manager and need to change some things to make sure all configs work.

**Comment by Khanx** [comment]
Okay, thanx for the info
